name: Docker

on:
  repository_dispatch:
    types: [publish]
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: false

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/eu4_legacy_wiki:test

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}        
